version: '3.9'
services:
  node:
    image: node:16
    container_name: app_delivery_node
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
  db:
    container_name: app_delivery_db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password